language: rust
dist: focal
sudo: true
group: edge
script:
  - sudo apt-get install --yes linux-modules-extra-"$(uname --kernel-release)"
  - cargo install cargo-valgrind
  - ./scripts/ci.sh
  - cargo build --verbose
  - for t in ./target/debug/deps/integration-*; do sudo valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes "${t}" can_send_rdma_loopback_traffic_on_test_device; done
#  - cargo test --verbose -- --test-threads=1 || true
#  - cargo valgrind test --verbose --test integration -- --test-threads=1 || true
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - gcc-10
    - ibverbs-providers
    - iproute2
    - jq
    - libibverbs-dev
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libudev-dev
    - ninja-build
    - valgrind
env:
  - RUST_BACKTRACE=1
rust:
  - nightly
  - beta
  - stable
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
