version: ~> 1.0
language: rust
os: linux
dist: focal
group: edge
script:
  - echo deb http://archive.ubuntu.com/ubuntu/ focal main restricted | sudo tee -a /etc/apt/sources.list
  - echo deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted | sudo tee -a /etc/apt/sources.list
  - echo deb http://archive.ubuntu.com/ubuntu/ focal universe | sudo tee -a /etc/apt/sources.list
  - echo deb http://archive.ubuntu.com/ubuntu/ focal-updates universe | sudo tee -a /etc/apt/sources.list
  - echo deb http://archive.ubuntu.com/ubuntu/ focal multiverse | sudo tee -a /etc/apt/sources.list
  - echo deb http://archive.ubuntu.com/ubuntu/ focal-updates multiverse | sudo tee -a /etc/apt/sources.list
  - echo deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse | sudo tee -a /etc/apt/sources.list
  - echo deb http://security.ubuntu.com/ubuntu/ focal-security main restricted | sudo tee -a /etc/apt/sources.list
  - echo deb http://security.ubuntu.com/ubuntu/ focal-security universe | sudo tee -a /etc/apt/sources.list
  - echo deb http://security.ubuntu.com/ubuntu/ focal-security multiverse | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-cache search ibverbs
  - sudo apt-cache search gcc-10
  - sudo apt-cache search gcc-11
  - sudo apt-cache search rdma
  - sudo apt-get install --yes linux-modules-extra-"$(uname --kernel-release)" ibverbs-providers
  - ./scripts/ci.sh
  - cargo build --verbose
  - cargo test --verbose -- --test-threads=1
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - gcc
    - iproute2
    - jq
    - libibverbs-dev
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libudev-dev
    - ninja-build
    - rdma-core
env:
  - RUST_BACKTRACE=1
rust:
  - nightly
  - beta
  - stable
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
