language: rust
dist: focal
sudo: true
group: edge
script:
  - ./scripts/ci.sh
  - cargo build --verbose
  - cargo test --verbose
before_install:
  - sudo apt-get --quiet update
  # We need to install linux-modules-extra for our current kernel or else we don't have access to the rdma_rxe module.
  - sudo apt-get install --yes linux-modules-extra-"$(uname --kernel-release)"
  - sudo modprobe rdma_rxe
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - docker
    - gcc-10
    - ibverbs-providers
    - iproute2
    - jq
    - libibverbs1
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libudev-dev
    - ninja-build
env:
  - RUST_BACKTRACE=1
rust:
  - nightly
  - beta
  - stable
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
